name: app_coffee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  http: ^0.13.6
  intl: ^0.18.0
  dio: ^5.1.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  badges: ^2.0.2
  buttons_tabbar: ^1.3.12
  dotted_line: ^3.2.2
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/files/

fonts:
  - family: Inter
    fonts:
      - assets: fonts/Inter-Bold.ttf
